#!/bin/bash -e

if [ "$1" == "" ]; then
    echo "Usage: [ sample_rate=SAMPLE_RATE ] [ showvolume=1 ] $0 NUM_CHANNELS [ OUTPUT_DIR ]"
    echo "  if showvolume=1, SDL-compatible display is required for showing the volume meters"
    exit 1
fi

num_channels=$1
output_dir="${2:-.}"
output_file="$output_dir/$(date +'%Y-%m-%d_%H-%M-%S').w64"
fifo=./output.raw
srate=${sample_rate:-48000}

test -p $fifo || mkfifo $fifo

if [ "$showvolume" == "1" ]; then
    showvol_flags="-filter_complex [0:a]asplit=2[a],showvolume[v] -map [v] -f sdl2 showvolume -map [a]"
else
    showvol_flags=
fi

ffmpeg -nostdin -fflags nobuffer -f s32le -sample_rate $srate -channels $num_channels -i $fifo $showvol_flags -c:a pcm_s24le $output_file &

INFERNO_SAMPLE_RATE=$srate RUST_LOG=debug RUST_BACKTRACE=1 cargo run --release -- -c $num_channels -o $fifo
